[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15"
clap = { version = "4.5", features = ["derive"] }
reqwest = { version = "0.12", features = ["blocking", "cookies"] }
